apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-secret
  namespace: git
spec:
  secretName: jenkins-secret
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
  commonName: jenkins.k8s.com
  dnsNames:
  - jenkins.k8s.com
